# Generated by Django 3.2.8 on 2021-10-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOrigin', models.ImageField(upload_to='')),
                ('imageBackground', models.ImageField(upload_to='')),
                ('imagePredict', models.ImageField(upload_to='')),
            ],
        ),
    ]
