# Generated by Django 3.2.8 on 2021-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='imageBackground',
            field=models.ImageField(default='depqua.jpg', upload_to=''),
        ),
    ]
