# Generated by Django 3.2.8 on 2021-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_holder_imagebackground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holder',
            name='imagePredict',
        ),
    ]
